### PR TITLE
Allow unsecure database connection in production

### PR DESCRIPTION
**Pull request by m42e**

### CODE REVIEW

**Comment by sungwoncho** [comment]
Thanks for taking time to make a pull request. Could you clarify the use case? Specifically, I would like to know the cases in which a user can benefit from disabling ssl mode.

**Comment by m42e** [comment]
For sure. In fact I have Outfit into a dicker container and setting up Postgres in docker with ssl is a bit of work, especially on a Synology where your shell access is limited. 
So having this would enable me to provide a simple docker-compose file to setup dnote in seconds. Using nonproductive mode does not help either, cause then sending mails is disabled.

**Comment by sungwoncho** [comment]
Sorry for the delay, I will test your PR this week.

**Comment by sungwoncho** [comment]
Thanks for your contribution.

**Pull request merged**
